const ACTypes = {
  INIT_STORIES: 'INIT_STORIES',
  SET_STORIES: 'SET_STORIES',
  CHANGE_STATUS_LOADING: 'CHANGE_STATUS_LOADING',
  CHANGE_STATUS_NOT_LOADING: 'CHANGE_STATUS_NOT_LOADING',
};

export default ACTypes;
